# Generated by Django 4.1 on 2022-08-23 13:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_alter_genre_options_alter_music_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('pdf_file', models.FileField(upload_to='scenarii/')),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
                ('min_player_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_player_number', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.IntegerField(choices=[(0, 'One shot'), (1, 'Mini-campaign'), (2, 'Campaign')], default=0)),
                ('vote', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('styles', models.ManyToManyField(to='music.style')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RolePlayGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('vf_editor', models.CharField(blank=True, max_length=200, null=True)),
                ('original_editor', models.CharField(max_length=200)),
                ('styles', models.ManyToManyField(to='music.style')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.system')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
