"""Added_by_user_id column added to Music model

Revision ID: 99ce859ab064
Revises: e88f663816eb
Create Date: 2022-08-04 13:46:55.916486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ce859ab064'
down_revision = 'e88f663816eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'music', 'user', ['added_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'music', type_='foreignkey')
    op.drop_column('music', 'added_by_user_id')
    # ### end Alembic commands ###
