# Generated by Django 4.1 on 2022-08-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['name']},
        ),
    ]
